kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: home-v1-binding
  namespace: meshdemons-v4
spec:
  virtualDeployment:
    ref:
      name: home-v1
      namespace: meshdemons-v4
  target:
    service:
      ref:
        name: home-v1
        namespace: meshdemons-v4
---
kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: home-v2-binding
  namespace: meshdemons-v4
spec:
  virtualDeployment:
    ref:
      name: home-v2
      namespace: meshdemons-v4
  target:
    service:
      ref:
        name: home-v2
        namespace: meshdemons-v4
---
