kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: details-v1-binding
  namespace: meshdemo
spec:
  virtualDeployment:
    ref:
      name: home-v1
      namespace: meshdemo
  target:
    service:
      ref:
        name: home
        namespace: meshdemo
---