kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: home-v1-binding
  namespace: meshdemons
spec:
  virtualDeployment:
    ref:
      name: home-v1
      namespace: meshdemons
  target:
    service:
      ref:
        name: home
        namespace: meshdemons
---
