apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: meshdemo_version
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-amsterdam-1.dfrpeul7aaaie.abqw2ljrkepslvp6wwxbwad26sgfhmlbh6i4ycnd7bj4rtc3sxnb4kj33faq
      region: eu-amsterdam-1
      