apiVersion: oci.oracle.com/v1beta1
kind: AutonomousDatabases
metadata:
  name: oracledb
  namespace: meshdemo_version
spec:
  compartmentId: meshdemo_compartment
  displayName: oracledb
  dbName: oracledb
  dbWorkload: OLTP
  isDedicated: false
  dbVersion: 19c
  dataStorageSizeInTBs: 1
  cpuCoreCount: 1
  adminPassword:
    secret:
      secretName: admin-secret
  isAutoScalingEnabled: false
  isFreeTier: false
  licenseModel: BRING_YOUR_OWN_LICENSE
  wallet:
    walletName: wallet
    walletPassword:
      secret:
        secretName: wallet-secret
  freeformTags:
  definedTags: 
